name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  batch: true
  branches:
    include:
    - main

variables:
  - group: azure-container-app

stages :
  - stage: create_acr
    jobs:
      - job: "create_acr"
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy RG and ACR'
            inputs:
              azureSubscription: 'Azure connection'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                #!/bin/bash

                RESOURCE_GROUP="azure-container-rg"
                LOCATION="westeurope"
                LOG_ANALYTICS_WORKSPACE="demoacrcontainersla"
                ACR="containersdemoregistry12"

                az group create -l $LOCATION -n $RESOURCE_GROUP
                az acr create -g $RESOURCE_GROUP -n $ACR --sku basic --admin-enabled true
                az monitor log-analytics workspace create -g $RESOURCE_GROUP --workspace-name $LOG_ANALYTICS_WORKSPACE
  - stage: Build
    dependsOn: [create_acr]
    displayName: Build sample app
    jobs:  
    - job: Build
      displayName: Build job
      steps:
      - task: Docker@2
        displayName: Build and push sample app to container registry
        inputs:
          command: buildAndPush
          repository: 'sampleapp'
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          containerRegistry: 'containersdemoregistry'
          tags: '$(Build.BuildId)'


  
